### ISSUE TITLE
wkwebview的scrollView 会导致滑动无效，如何解决呢

### ISSUE THREAD

**Issue by jiazufei** [lmf12/MFNestTableView#6]
这样写也不灵
- (void)nestTableViewContainerCanScroll:(MFNestTableView *)nestTableView {
    
    // 当容器开始可以滚动时，将所有内容设置回到顶部
    for (id view in self.viewList) {
        UIScrollView *scrollView;
        if ([view isKindOfClass:[UIScrollView class]]) {
            scrollView = view;
        } else if ([view isKindOfClass:[WKWebView class]]) {
            scrollView = ((WKWebView *)view).scrollView;
        }
        if (scrollView) {
            scrollView.contentOffset = CGPointZero;
        }
    }
}

**Comment by lmf12** [comment]
@jiazufei 另外，这个地方也加个判断试试。
- (BOOL) gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    id view = otherGestureRecognizer.view;
    if ([[view superview] isKindOfClass:[UIWebView class]]) {
        view = [view superview];
    } else if ([[view superview] isKindOfClass:[WKWebView class]]) {
        view = [view superview];
    }
    
    if (_allowGestureEventPassViews && [_allowGestureEventPassViews containsObject:view]) {
        return YES;
    } else {
        return NO;
    }
}

**Comment by jiazufei** [comment]
先用uiwebview吧，我现在有个问题 _canContentScroll初始值是NO，而且通过header划上去也会变成NO，导致下边的子视图滑动失效了，一直走这个条件， if (!_canContentScroll) {

// tableView，scrollView，webView滑动时都会响应这个方法
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    NSLog(@"scrollViewDidScroll _canContentScroll = %@",_canContentScroll?@"YES":@"NO");
    if (!_canContentScroll) {
        // 这里通过固定contentOffset，来实现不滚动
        NSLog(@"这里通过固定contentOffset，来实现不滚动");
        scrollView.contentOffset = CGPointZero;
    } else if (scrollView.contentOffset.y <= 0) {
        NSLog(@"通知容器可以开始滚动");
        _canContentScroll = NO;
        // 通知容器可以开始滚动
        _nestTableView.canScroll = YES;
    }
    scrollView.showsVerticalScrollIndicator = _canContentScroll;
}

**Comment by lmf12** [comment]
@jiazufei 通过 header 来滑动，只会触发外层的 ScrollView 滑动，不会触发子 ScrollView 的滑动，因为触摸点不在子 ScrollView  的范围内。所以应该是 `scrollViewDidScroll` 整个方法都不会走才对。
解决这个问题，可以重写 `MFNestTableView` 的 `hitTest: withEvent:` 方法，将 header 的触摸事件转发给当前显示的子 ScrollView 。

**Comment by jiazufei** [comment]
照着demo写的，没做什么修改，demo的效果符合需求，我写的子视图就是不动啊

**Comment by jiazufei** [comment]
我的问题，子视图加载放layout后边了，问题解决了
